Repository ToltekPlus/lamoda, pull requests merged in 2023-05, with the labels that each got.

#45 Добавлен vuex
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/src/main.js
  nodejs/src/store/index.js
Labels: 📢 enhancement, 🚸 good first issue, 📡 workflow

#48 'npm lint' запускается вместе с 'npm start'
  nodejs/package-lock.json
  nodejs/package.json
Labels: 📗 documentation, 📢 enhancement, 🚸 good first issue, 📡 workflow

#51 Describe the api for working with the database
  README.md
  docker-compose.yml
  nginx/Dockerfile
  nginx/default.conf
  nodejs/.gitignore
  nodejs/Dockerfile
  nodejs/README.md
  nodejs/babel.config.js
  nodejs/jsconfig.json
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/public/images/logo.svg
  nodejs/public/index.html
  nodejs/src/App.vue
  nodejs/src/components/Header/App.vue
  nodejs/src/components/Header/components/Cart/CartComponent.vue
  nodejs/src/components/Header/components/Favorite/FavoriteComponent.vue
  nodejs/src/components/Header/components/Logotype/LogotypeComponent.vue
  nodejs/src/components/Header/components/Navigation/NavigationComponent.vue
  nodejs/src/components/Header/components/Search/SearchComponent.vue
  nodejs/src/components/Header/components/User/UserComponent.vue
  nodejs/src/components/Header/data/cart.json
  nodejs/src/components/Header/data/navigation.json
  nodejs/src/main.js
  nodejs/src/router/index.js
  nodejs/src/store/index.js
  nodejs/src/views/ChildrenView.vue
  nodejs/src/views/FavoriteView.vue
  nodejs/src/views/HomeView.vue
  nodejs/src/views/MenView.vue
  nodejs/src/views/UserView.vue
  nodejs/src/views/WomenView.vue
  nodejs/src/views/main.js
  nodejs/vue.config.js
  php/Dockerfile
  php/README.md
  php/api/index.php
  php/db/dump/init.sql
  php/db/migrations/20230121072756_user_table.php
  php/db/migrations/20230123155144_account_table.php
  php/db/migrations/20230123162345_account_user_table.php
  php/db/seeds/AccountSeeder.php
  php/db/seeds/AccountUserSeeder.php
  php/db/seeds/MainSeeder.php
  php/db/seeds/UserSeeder.php
  php/services/.env.dev
  php/services/.htaccess
  php/services/composer.json
  php/services/composer.lock
  php/services/env.php
  php/services/images/amanda.jpg
  php/services/images/eva.jpg
  php/services/images/monika.jpg
  php/services/index.php
  php/services/phinx.dev.json
  php/services/phinx.json
  php/services/src/Controller/HomeController.php
  php/services/src/Core/Database.php
  php/services/src/Core/Model.php
  static/script.js
Labels: 📗 documentation, 📢 enhancement, ❗ 🔞 help wanted, 🗺️ API, 🤼 conflicts, 📡 workflow

#55 Front 13 catalog component
  nodejs/package.json
  nodejs/src/App.vue
  nodejs/src/components/Catalog/App.vue
  nodejs/src/components/Catalog/components/AddToCart.vue
  nodejs/src/components/Catalog/components/AddToFavorite.vue
  nodejs/src/components/Catalog/components/Product.vue
  nodejs/src/components/Header/App.vue
  nodejs/src/components/Header/components/Cart/CartComponent.vue
  nodejs/src/components/Header/components/Favorite/FavoriteComponent.vue
  nodejs/src/components/Header/components/Modal/Modal.vue
  nodejs/src/main.js
  nodejs/src/store/index.js
  nodejs/src/store/modules/cart.js
  nodejs/src/store/modules/favorite.js
Labels: 📢 enhancement
